In [7]:
from sqlalchemy import create_engine
import pandas as pd

# ✅ Correct connection
engine = create_engine("mysql+pymysql://root:Satyam%401234@localhost:3306/quick_commerce")

# ✅ Test query
df = pd.read_sql("SELECT * from customers", engine)

print(df)

      customer_id  customer_name       city signup_date
0               1     Customer_1  Hyderabad  2023-03-23
1               2     Customer_2    Chennai  2023-01-19
2               3     Customer_3      Delhi  2023-07-20
3               4     Customer_4    Chennai  2023-06-28
4               5     Customer_5    Chennai  2023-06-12
...           ...            ...        ...         ...
4995         4996  Customer_4996  Hyderabad  2023-12-12
4996         4997  Customer_4997  Hyderabad  2023-01-26
4997         4998  Customer_4998    Chennai  2023-04-09
4998         4999  Customer_4999  Hyderabad  2023-12-17
4999         5000  Customer_5000    Chennai  2023-04-24

[5000 rows x 4 columns]

In [1]:
import requests
import pandas as pd

url = "https://api.coingecko.com/api/v3/coins/markets"

params = {
    "vs_currency": "usd",
    "per_page": 100
}

data = requests.get(url, params=params).json()

df = pd.DataFrame(data)

print(df.head())

            id symbol      name  \
0      bitcoin    btc   Bitcoin
1     ethereum    eth  Ethereum
2       tether   usdt    Tether
3  binancecoin    bnb       BNB
4       ripple    xrp       XRP

                                               image  current_price  \
0  https://coin-images.coingecko.com/coins/images...   68911.000000
1  https://coin-images.coingecko.com/coins/images...    2065.390000
2  https://coin-images.coingecko.com/coins/images...       0.999416
3  https://coin-images.coingecko.com/coins/images...     626.460000
4  https://coin-images.coingecko.com/coins/images...       1.360000

      market_cap  market_cap_rank  fully_diluted_valuation  total_volume  \
0  1377335095778                1            1377335095778  4.397121e+10
1   249090790430                2             249090790430  1.594656e+10
2   184092290456                3             189555541658  6.862607e+10
3    85351594436                4              85351594436  8.606769e+08
4    83567474084                5             136206841767  1.998112e+09

      high_24h  ...  total_supply    max_supply        ath  \
0  71472.00000  ...  2.000304e+07  2.100000e+07  126080.00
1   2178.23000  ...  1.206915e+08           NaN    4946.05
2      0.99979  ...  1.896835e+11           NaN       1.32
3    649.03000  ...  1.363574e+08  2.000000e+08    1369.99
4      1.42000  ...  9.998570e+10  1.000000e+11       3.65

   ath_change_percentage                  ath_date        atl  \
0              -45.34361  2025-10-06T18:57:42.558Z  67.810000
1              -58.24149  2025-08-24T19:21:03.333Z   0.432979
2              -24.46324  2018-07-24T00:00:00.000Z   0.572521
3              -54.27245  2025-10-13T08:41:24.131Z   0.039818
4              -62.64165  2025-07-18T03:40:53.808Z   0.002686

   atl_change_percentage                  atl_date  \
0           1.015247e+05  2013-07-06T00:00:00.000Z
1           4.769201e+05  2015-10-20T00:00:00.000Z
2           7.456535e+01  2015-03-02T00:00:00.000Z
3           1.573230e+06  2017-10-19T00:00:00.000Z
4           5.061191e+04  2014-05-22T00:00:00.000Z

                                                 roi              last_updated
0                                               None  2026-03-26T16:35:50.884Z
1  {'times': 39.08310777513541, 'currency': 'btc'...  2026-03-26T16:35:51.056Z
2                                               None  2026-03-26T16:35:59.022Z
3                                               None  2026-03-26T16:35:50.760Z
4                                               None  2026-03-26T16:35:56.510Z

[5 rows x 26 columns]

In [2]:
df = df[['id','name','market_cap', 'current_price', 'total_volume']].copy()
df.columns = ['coin','coin_name','market_cap','price','volume']
df

,coin,coin_name,market_cap,price,volume
0,bitcoin,Bitcoin,1377335095778,68911.000000,4.397121e+10
1,ethereum,Ethereum,249090790430,2065.390000,1.594656e+10
2,tether,Tether,184092290456,0.999416,6.862607e+10
3,binancecoin,BNB,85351594436,626.460000,8.606769e+08
4,ripple,XRP,83567474084,1.360000,1.998112e+09
...,...,...,...,...,...
95,layerzero,LayerZero,534483669,2.120000,5.364466e+07
96,jupiter-exchange-solana,Jupiter,523387137,0.149659,2.105368e+07
97,bonk,Bonk,519552799,0.000006,4.276388e+07
98,just,JUST,516114633,0.058551,1.164483e+08
99,true-usd,TrueUSD,493491634,0.998208,7.808412e+06

In [3]:
df = df.dropna()

df = df.drop_duplicates()

df['price'] = pd.to_numeric(df['price'],errors = 'coerce')

df = df[df['price']>0]

In [4]:
from datetime import datetime
df['timestamp'] = datetime.now()

In [5]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Satyam%401234@localhost:3306/crypto_api")

df.to_sql("crypto_data", con=engine, if_exists='append', index=False)

100

In [11]:
df.groupby('coin')['price'].std().sort_values(ascending = False)

coin
aave                      NaN
algorand                  NaN
aptos                     NaN
arbitrum                  NaN
aster-2                   NaN
                           ..
world-liberty-financial   NaN
worldcoin-wld             NaN
xdce-crowd-sale           NaN
ylds                      NaN
zcash                     NaN
Name: price, Length: 100, dtype: float64

In [13]:
df['rolling_avg'] = df['price'].rolling(5).mean()

In [15]:
df.head()

,coin,coin_name,market_cap,price,volume,timestamp,rolling_avg
0,bitcoin,Bitcoin,1377335095778,68911.000000,4.397121e+10,2026-03-26 22:06:37.181372,NaN
1,ethereum,Ethereum,249090790430,2065.390000,1.594656e+10,2026-03-26 22:06:37.181372,NaN
2,tether,Tether,184092290456,0.999416,6.862607e+10,2026-03-26 22:06:37.181372,NaN
3,binancecoin,BNB,85351594436,626.460000,8.606769e+08,2026-03-26 22:06:37.181372,NaN
4,ripple,XRP,83567474084,1.360000,1.998112e+09,2026-03-26 22:06:37.181372,14321.041883

In [17]:
#4. Volume vs Price Relationship
# What it means
#Does higher trading volume increase price?

In [19]:
df[['price','volume']].corr()

#moderate correlation not a strong correlation lies in the range of (0.25-0.75)

           price    volume
price   1.000000  0.519746
volume  0.519746  1.000000

In [21]:
#5. Top Gainers & Losers
#What it means
#Which coins increased/decreased most?

In [23]:
df['price_change'] = df.groupby('coin')['price'].transform(lambda x: x.max() - x.min())

In [25]:
df.head()

,coin,coin_name,market_cap,price,volume,timestamp,rolling_avg,price_change
0,bitcoin,Bitcoin,1377335095778,68911.000000,4.397121e+10,2026-03-26 22:06:37.181372,NaN,0.0
1,ethereum,Ethereum,249090790430,2065.390000,1.594656e+10,2026-03-26 22:06:37.181372,NaN,0.0
2,tether,Tether,184092290456,0.999416,6.862607e+10,2026-03-26 22:06:37.181372,NaN,0.0
3,binancecoin,BNB,85351594436,626.460000,8.606769e+08,2026-03-26 22:06:37.181372,NaN,0.0
4,ripple,XRP,83567474084,1.360000,1.998112e+09,2026-03-26 22:06:37.181372,14321.041883,0.0

In [ ]:
#6. Liquidity Risk Analysis
What it means?
-Can you easily buy/sell this coin?
-Low volume = risky

Why it matters?
-Avoid coins that are hard to sell
-Important for big investors

In [27]:
df['liquidity_ratio'] = df['volume']/df['market_cap']
df.sort_values(by = 'liquidity_ratio')

,coin,coin_name,market_cap,price,volume,timestamp,rolling_avg,price_change,liquidity_ratio
42,blackrock-usd-institutional-digital-liquidity-...,BlackRock USD Institutional Digital Liquidity ...,2112550212,1.000000,0.000000e+00,2026-03-26 22:06:37.181372,879.755048,0.0,0.000000
65,janus-henderson-anemoy-treasury-fund,Janus Henderson Anemoy Treasury Fund,1040253723,1.098000,0.000000e+00,2026-03-26 22:06:37.181372,17.771955,0.0,0.000000
80,superstate-short-duration-us-government-securi...,Superstate Short Duration U.S. Government Secu...,740123680,11.030000,0.000000e+00,2026-03-26 22:06:37.181372,2.638804,0.0,0.000000
87,ousg,OUSG,621108158,114.700000,0.000000e+00,2026-03-26 22:06:37.181372,23.141401,0.0,0.000000
68,eutbl,Spiko EU T-Bills Money Market Fund,953800215,1.210000,0.000000e+00,2026-03-26 22:06:37.181372,0.488031,0.0,0.000000
...,...,...,...,...,...,...,...,...,...
21,usd1-wlfi,USD1,4415114895,0.999139,1.180256e+09,2026-03-26 22:06:37.181372,65.357431,0.0,0.267322
37,tether-gold,Tether Gold,2454368365,4386.960000,7.484305e+08,2026-03-26 22:06:37.181372,877.908260,0.0,0.304938
93,fetch-ai,Artificial Superintelligence Alliance,548407413,0.242975,1.814606e+08,2026-03-26 22:06:37.181372,0.666997,0.0,0.330886
2,tether,Tether,184092290456,0.999416,6.862607e+10,2026-03-26 22:06:37.181372,NaN,0.0,0.372781
77,midnight-3,Midnight,799912866,0.048213,1.212194e+09,2026-03-26 22:06:37.181372,0.775540,0.0,1.515408

In [ ]:
# 7. Portfolio Diversification
What it means?
-Don’t invest in similar coins only

Why it matters?
-Reduces risk
-Smart investment strategy

In [39]:
#price change percent

df['price_change_pct'] = df.groupby('coin')['price'].pct_change()

In [45]:
pivot_df = df.pivot(index='timestamp', columns='coin', values='price')

# Fill missing values
pivot_df = pivot_df.fillna(method='ffill')

# Calculate returns
returns = pivot_df.pct_change()

# Correlation
corr_matrix = returns.corr()